# Generated by Django 4.0.1 on 2022-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(help_text='This field is required!', max_length=200)),
                ('student_address', models.CharField(help_text='This field is required!', max_length=100)),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('student_email', models.EmailField(max_length=100, null=True)),
                ('student_phone', models.PositiveBigIntegerField(help_text='This field is required!', max_length=10)),
                ('addmission_date', models.DateField()),
                ('student_image', models.ImageField(default='default.jpg', null=True, upload_to='customer_images')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
