# Generated by Django 4.0.1 on 2022-02-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0003_alter_student_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=10),
        ),
    ]
