# Generated by Django 4.0.1 on 2022-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0004_student_student_class_alter_student_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.PositiveSmallIntegerField(max_length=100, null=True),
        ),
    ]
