# Generated by Django 4.0.1 on 2022-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0009_alter_student_addmission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
